### ISSUE TITLE
`NativeScript discarding uncaught exception!`

### ISSUE THREAD

**Issue by jasongitmail** [timdoege/nativescript-geocoding#12]
@timdoege thanks for making this plugin!

I'm using it within `app.ts` of my Svelte Native, NativeScript app.

`await geolocation.enableLocationRequest();` and `const { latitude, longitude } = await geolocation.getCurrentLocation()` both work and return the lat and long.

### Problem

However, attempting to invoke  `const result = await geocoding.getFromLocation(latitude, longitude, 1);` from this plugin, causes a momentary flash of the below error and then runs successfully, even though my code uses a try/catch around all 3 of these methods (and no error is logged to the console, weirdly).

![image](https://github.com/nativescript-community/geocoding/assets/50032291/6b3bd076-0728-445e-b47a-9d30d3c9b846)

### Likely cause

My hunch is this plugin requires the SvelteNative app itself to have launched before it will run successfully, which explains why the error is momentary. 

I believe this b/c 1.) my GPS-related code previously used chained promises and `geocoding.getFromLocation()` ran without an error, but this flow allowed the Svelte Native app to launch _before_ `geocoding.getFromLocation()` was invoked; the app would launch with old data and then refresh to use the current GPS info, but avoided this error.

When 2.) I refactored to `async/await` syntax, then the error in the screenshot occurs; my goal of using async/await is to block invocation of the SvelteNative app until all 3 of the GPS-realted methods finish, to prevent a flash of the app before it has the current GPS data.

### Question / suggested solution

Could it be possible to refactor this plugin to behave more like `geolocation.enableLocationRequest()` and `await geolocation.getCurrentLocation()`,  so it can work even when the SvelteNative app hasn't launched yet within `app.ts`?

### Versions

```json
"@nativescript/core": "~8.6.2",
"@nativescript/geolocation": "^8.3.1",
"@nativescript-community/geocoding": "^3.1.0",
"svelte-native": "~1.0.15"
```

Running for ios.

**Comment by vallemar** [comment]
@jasongitmail hello! a quick solution would be to run your code once your app has started, you could do it like this
```ts

Application.on('initRootView', (args: ApplicationEventData) => {
  // your code
})

```
Doc https://docs.nativescript.org/core/application#cross-platform-application-events

**Comment by jasongitmail** [comment]
Thanks @vallemar! I was able to come up with a solution for my needs using this event.  

Going to close this issue because, looking at the plugin code, it's unclear what could even be changed to allow the plugin run before app initialization. The code seems quite simple.
