### ISSUE TITLE
Missing getAdminArea() method in Android Location class

### ISSUE THREAD

**Issue by ignacio68** [timdoege/nativescript-geocoding#7]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
the getAdminArea() method is missing in Android implementation. 

### Which platform(s) does your issue occur on?
Android

### Is there any code involved? 
geocoding.android.ts
            this.administrativeArea = androidLocation.getAdminArea()

export class Location extends LocationBase {
    public android: android.location.Address;

    constructor(androidLocation: android.location.Address) {
        super();
        if (androidLocation) {
            this.android = androidLocation;
            this.name = androidLocation.getFeatureName();
            this.latitude = androidLocation.getLatitude();
            this.longitude = androidLocation.getLongitude();
            this.country = androidLocation.getCountryName();
            this.isoCountryCode = androidLocation.getCountryCode();
            this.locality = androidLocation.getLocality();
            this.postalCode = androidLocation.getPostalCode();
            ->> this.administrativeArea = androidLocation.getAdminArea();
            this.subLocality = androidLocation.getSubLocality();
            this.subThoroughfare = androidLocation.getSubThoroughfare();
            this.thoroughfare = androidLocation.getThoroughfare();
        }
    }
}

**Comment by timdoege** [comment]
Fixed in 2.0.2
